### ISSUE TITLE
Clarity formatted for test coverage

### ISSUE THREAD

**Issue by njordhov** [PromptECO/clariform#23]
To accommodate test tooling, Clariform can format Clarity with a single line per branch/expression, or split each expression over multiple lines.

Test coverage is misreported by tooling for Clarity as they're typically line-oriented while expressions and branches in Clarity can span multiple lines. 

https://github.com/Trust-Machines/core-eng/issues/305

**Comment by friedger** [comment]
With clarinet 1.7.0 we have better code coverage. This issue can be closed, I think.
